name: Think and Speak - Build & Push Docker

on:
  release:
    types: [published]

jobs:
  action_trigger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: get tag info
        uses: Seechange-edu/Parse-Action-Tag@main
        with:
          githubToken: ${{ secrets.ACTION_TOKEN }}
          type: parse

      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: SeeChange-edu/${{ env.REPOSITORY }}
          token: ${{ secrets.ACTION_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: corretto
          cache: maven

      - name: Maven Build
        run: mvn package -T 1C -D skipTests -D fast

      - name: Setup AWS ECR Details (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-ECR-Push
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          ACTIVE: ${{ env.ACTIVE }}
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}/${ACTIVE}:${ACTIVE}"
          docker build --tag ${IMAGE_URI} --file Dockerfile-Self .
          docker push ${IMAGE_URI}
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      - name: Get ECR login token
        id: ecr-login-token
        run: |
          ECR_TOKEN=$(aws ecr get-login-password --region ${{ vars.AWS_REGION }})
          echo "token<<EOF" >> $GITHUB_OUTPUT
          echo "$ECR_TOKEN" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: SSH and Run Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.AWS_DEVELOPMENT_SERVER_IP }}
          username: ${{ vars.AWS_DEVELOPMENT_SERVER_LOGIN }}
          key: ${{ secrets.REMOTE_AWS_DEV_PRIVATE_SSH_KEY }}
          envs: ECR_REGISTRY,ECR_REPOSITORY,ACTIVE,ECR_TOKEN
          script: |
            # Login to AWS ECR using temporary token from GitHub Actions
            echo ${ECR_TOKEN} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
            
            IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}/${ACTIVE}:${ACTIVE}"
            docker pull ${IMAGE_URI}
            if [ "$(docker ps -a --format '{{.Names}}' | grep -c ${{ env.NAME }})" -gt 0 ]; then 
              docker rm -f ${{ env.NAME }}
            fi
            docker run --name ${{ env.NAME }} -d -p ${{ env.OUT_PORT }}:${{ env.PORT }} -p ${{ env.OUT_PORT1 }}:${{ env.PORT1 }} ${{ env.RUN_ARGS }} --restart unless-stopped ${IMAGE_URI}
            docker image prune --force
            docker container prune --force
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          ACTIVE: ${{ env.ACTIVE }}
          ECR_TOKEN: ${{ steps.ecr-login-token.outputs.token }}

  notify-teams:
    if: always()
    needs: [ action_trigger ]
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        env:
          WEBHOOK: ${{ vars.TEAMS_WEBHOOK_URL }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "${{ needs.action_trigger.result == 'success' && '00FF00' || 'FF0000' }}",
            "summary": "${{ needs.action_trigger.result == 'success' && 'üéâ Build succeeded!' || '‚ùå Build failed!' }}:${{ github.repository }}:${{ github.workflow }}",
            "title": "${{ needs.action_trigger.result == 'success' && 'üéâ Build succeeded!' || '‚ùå Build failed!' }}:${{ github.repository }}:${{ github.workflow }}",
            "sections": [{
              "facts": [
                { "name": "Repository", "value": "${{ github.repository }}" },
                { "name": "Triggered by", "value": "${{ github.event_name }}" },
                { "name": "Commit Message", "value": "${{ github.event.head_commit.message }}" },
                { "name": "Author", "value": "@${{ github.actor }}" },
                { "name": "Result", "value": "${{ needs.action_trigger.result }}" }
              ],
              "text": "[View Workflow Run](${{ env.RUN_URL }})"
            }]
          }' \
          "$WEBHOOK"